### ISSUE TITLE
Error in asset

### ISSUE THREAD

**Issue by FaraFara** [m2sd/typoscript-webpack-plugin#1]
Hello!

Iam got this error:

 **const extension = asset.match(/\.(js|css)$/)[1];
                                                        ^

TypeError: Cannot read property '1' of null
    at options.files.forEach.asset (/node_modules/typoscript-webpack-plugin/index.js:108:57)**

Where is problem?

**Comment by mentAl-maZe** [comment]
The reported issue should be resolved.

Additionally I published the next minor version (it was tagged as `next` on npm because i hadn't yet updated the documentation).
Check out the new loading functionality :grin: 

Please close if your issue was resolved.

PS: I'd still be curious to see your `webpack.config.js`. If at all possible, could you post it on this thread?

**Comment by FaraFara** [comment]
Thanks!
In version 1.2.4 issue was resolved.
But, iam find another little bug.

I have two webpack config: one for Production, and another for WebpackDevServer.
Also, generated manifest.json for all config

Production:
{
  "vendors-confetti-vue.js": "/Public/Dist/JS/vendors-confetti-vue.3d208e54d55f02c50947.js",
  "vendors-confetti-vue.js.map": "/Public/Dist/JS/vendors-confetti-vue.3d208e54d55f02c50947.js.map",
  "app.js": "/Public/Dist/JS/app.43114821d25dde67111f.js",
  "app.js.map": "/Public/Dist/JS/app.43114821d25dde67111f.js.map",
  "confetti.js": "/Public/Dist/JS/confetti.75b9792693e2fd501fbe.js",
  "confetti.js.map": "/Public/Dist/JS/confetti.75b9792693e2fd501fbe.js.map",
  "../../WebpackAssets.typoscript": "/Public/Dist/../../WebpackAssets.typoscript"
}

WebpackDevServer:
{
  "app.js": "http://1.1.1.1:8080/JS/app.7a78e8ff6bb9a46fd24d.js",
  "confetti.js": "http://1.1.1.1:8080/JS/confetti.7a78e8ff6bb9a46fd24d.js",
  "vendors-confetti.js": "http://1.1.1.1:8080/JS/vendors~confetti.7a78e8ff6bb9a46fd24d.js",
  "vendors-confetti-vue.js": "http://1.1.1.1:8080/JS/vendors-confetti-vue.7a78e8ff6bb9a46fd24d.js",
  "../../WebpackAssets.typoscript": "http://1.1.1.1:8080/../../WebpackAssets.typoscript"
}

You can see **"../..."** in  file name WebpackAssets.typoscript.
This prevent handling config.

**Comment by mentAl-maZe** [comment]
The key of the assets array is not a file name, but the file path relative to the output folder.
Your output folder seems to be `/Public/Dist/` if the `WebpackAssets.typoscript` file is to be written to the root directory the file path `../../WebpackAssets.typoscript` is correct.

Of course a relative path won't work for the dev-server, but a TypoScript file should never be served in the browser anyway.

In what context do you use the dev-server?

**Comment by mentAl-maZe** [comment]
PS: Do use [manifest-revision-webpack-plugin](https://github.com/nickjj/manifest-revision-webpack-plugin)? Or have you written a custom implementation to generate the manifest?

**Comment by FaraFara** [comment]
Dev-server in development context.
Iam set output folder in "/", and again key is "../..WebpackAssets.typoscript".

Theoretically, in development mode, i want include content of http://1.1.1.1:8080/WebpackAssets.typoscript
in typoscript. maybe I'm thinking wrong? has another way?

.....Also in Production key is "../..":
 ../../WebpackAssets.typoscript  329 bytes          [emitted]
                         JS/app.5abc05b4d96b36403770.js   2.58 KiB       1  [emitted]  app
                     JS/app.5abc05b4d96b36403770.js.map   11.8 KiB       1  [emitted]  app

Used webpack-manifest-plugin.
At all the webpack-manifest-plugin not need. Iam use him for testing generated links.

**Comment by FaraFara** [comment]
Iam solve this, applying path:

/*
        const outputPath = path.join(
            path.relative(
                compilation.options.output.path,
                this.options.outputPath
            ),
            this.options.filename
        );
*/
        const outputPath = this.options.filename;

**Comment by mentAl-maZe** [comment]
Hmm, interesting...

Could you please post your webpack setup (build and dev configs), or create a [gist](https://gist.github.com) so I can test this locally.

Your fix brakes functionality for me as I need to output the file to a different folder than the webpack output folder.

Here is an example of a production use case from one of my projects:
[EXT:typo3_site_package/Resources/Private/Asstes/config/webpack/base.conf.js](https://gist.github.com/mentAl-maZe/86d9adc2c543cb2cd97e1e60d051832b)

**Comment by FaraFara** [comment]
This is early draft webpack configs:
https://gist.github.com/FaraFara/05ddf253a8754293b6edad1cbb46cfe2

One problem is not resolved: How include content from url (http://1.1.1.1:8080/WebpackAssets.typoscript) in main typoscript file.

Deciding this, can be used full power Hot Module Reload from webpack

**Comment by mentAl-maZe** [comment]
Well, color me impressed :astonished:
Are you using a Vue frontend on top of a Typo3 backend?
I tried this myself but I gave up half way... :sweat_smile: 
Maybe you could teach me some tricks sometime :smile: 

The intended use case for the output file (`WebpackAssets.typoscript`) would be to include it into your typoscript setup manually.
A simple typoscript include in your main typoscript setup should suffice

For example in `typo3_site_package/Configuration/TypoScript/setup.txt`:

```typoscript
# ...
<INCLUDE_TYPOSCRIPT: source="FILE:EXT:typo3_site_package/Configuration/TypoScript/Config/Page/WebpackAssets.t3s">
# ...
```

The output file should regenerate just fine in watch mode.
With your Typo3 environment set to `development` the typoscript configuration normally would not be cached and a page refresh should trigger the update.

The HTML is generated by Typo3 on the server side, therefore I did not even consider HMR (hot module replacement).
HMR does not trigger a full page reload.

Theoretically, if you managed to configure your devServer properly (i.e. it uses the generated HTML from Typo3 backend or a corresponding template and assets can be resolved), HMR should find your assets just fine and replace them correctly, all you would need to do at that point is to exclude `WebpackAssets.typoscript` somehow from HMR as it should never find a corresponding resource on the client side...

Come to think of it, maybe I shouldn't add the typoscirpt file to the assets at all :thinking:

**Comment by FaraFara** [comment]
OK, this is my thoughts on HMR + Typo3.
After dev-server processed assets, we should get http://dev.server.ip:8080/WebpackAssets.typoscript

http://dev.server.ip:8080/WebpackAssets.typoscript must contain file path together url.
Like this:
customPageType {
includeJSFooter {
mainPage = http://dev.server.ip:8080/JS/app.7a78e8ff6bb9a46fd24d.js
mainPage.external = 1
}
includeCSS {
mainPage = http://dev.server.ip:8080/CSS/styles.7a78e8ff6bb9a46fd24d.css
mainPage.external = 1
}
}

Well done. HMR work.

One problem remained. How inlcude  http://dev.server.ip:8080/WebpackAssets.typoscript in main typoscript. <INCLUDE .... not suppurt URL, only FILES or DIR.

**Comment by mentAl-maZe** [comment]
Oooh... never thought of that, I must try this in my next project :smile: 

However, regarding typoscript, I don't really see a way to implement this sensibly.
Typoscript Is a server side scripting language and requires a PHP environment to be compiled.
The `<INCLUDE ...>` syntax does not support URL by design as that would mean the server (PHP) would need to trigger a synchronous request to an external resource before continuing to process the typoscript.
As typoscript is basically a configuration syntax for a server side framework the authors did not provide such option as this would slow down the rendering process considerably and the use cases are very limited at best.
And even if it were possible you would have to trigger a recompilation of your templates every time HMR replaces `WebpackAssets.typoscript`.

You could however exclude `WebpackAssets.typoscript` from HMR (i will remove it from assets in next version) and proxy everything except the assets in your devServer to your Typo3 server.
In theory that should keep HMR intact.

Example configuration:
**Disclaimer:** I have not yet tested this.

```js
module.exports = {
    //...
    devServer: {
        // ...
        index: '', // specify empty string to enable root proxying
        proxy: {
            // set empty context to proxy everything
            context: () => true,
            // skip proxy for non html requests
            bypass: req => (req.headers.accept.indexOf('html') !== -1),
            // proxy to php server
            target: 'http://localhost:8000',
        }
    }
};
```

**Comment by mentAl-maZe** [comment]
Also you could use a plugin such as [php-loader](https://www.npmjs.com/package/php-loader) or [webpack-php-loader](https://www.npmjs.com/package/webpack-php-loader)

**Comment by mentAl-maZe** [comment]
Alternatively consider using [webpack-livereload-plugin](https://www.npmjs.com/package/webpack-livereload-plugin) instead of webpack-dev-server.

**Comment by FaraFara** [comment]
> And even if it were possible you would have to trigger a recompilation of your templates every time HMR replaces WebpackAssets.typoscript.

No. Only need to connect once WebpackAssets.typoscript in main typoscript file and you may make any changes in asset (JS, CSS). HMR work well. I am manual insert in typoscript. All works fine.

If you change Templates OR Layout in TYPO3. Webpack may **fully** reload page. And TYPO3 rerendered page. I implemented this in my configs.

You are required to implement fhis feature: insert URL in development against file:
mainPage = **http://dev.server.ip:8080/JS/app.js**

That's possible?

**Comment by mentAl-maZe** [comment]
> No. Only need to connect once WebpackAssets.typoscript in main typoscript file and you may make any changes in asset (JS, CSS). HMR work well. I am manual insert in typoscript. All works fine.

That's what I meant, if you generate your templates with the assets in place HMR should work, without the need to reload `WebpackAssets.typoscript`.

> You are required to implement this feature: insert URL in development against file:
> mainPage = http://dev.server.ip:8080/JS/app.js

That should not be a problem.
In theory you could already do this by changing the `typoScriptPublicPath` option in your settings (see [webpack.settings.js](https://gist.github.com/FaraFara/05ddf253a8754293b6edad1cbb46cfe2#file-webpack-settings-js-L73)) to `http://dev.server.ip:8080/Dist/`.
Maybe check for `NODE_ENV` and overwrite the setting?

I could implement an additional dev prefix property but I'm not sure this is necessary, please let me know.

**Comment by mentAl-maZe** [comment]
PS: Could you point me to where you implemented the conditional full reload in your settings?
Just out of curiosity :sweat_smile: 
As stated before I'd like to try this myself sometime.
In your settings you seem to set `devServer: { hotOnly: true }` which would prevent a full reload, wouldn't it?

**Comment by FaraFara** [comment]
> That's what I meant, if you generate your templates with the assets in place HMR should work, without the need to reload `WebpackAssets.typoscript`.

Yes. Right.

**Comment by FaraFara** [comment]
> In theory you could already do this by changing the `typoScriptPublicPath` option in your settings (see [webpack.settings.js](https://gist.github.com/FaraFara/05ddf253a8754293b6edad1cbb46cfe2#file-webpack-settings-js-L73)) to `http://dev.server.ip:8080/Dist/`.
> Maybe check for `NODE_ENV` and overwrite the setting?

Good idea.

**Comment by FaraFara** [comment]
> PS: Could you point me to where you implemented the conditional full reload in your settings?
> Just out of curiosity 😅

See in webpack.dev.js this code:
 // Use sane to monitor all of the templates files and sub-directories
        before: (app, server) => {
            const watcher = sane(path.join(__dirname, settings.paths.templates), {
                glob: ['**/*'],
                poll: !!parseInt(settings.devServerConfig.poll()),
            });
            watcher.on('change', function(filePath, root, stat) {
                console.log('  File modified:', filePath);
                server.sockWrite(server.sockets, "content-changed");
            });
        },
settings.paths.templates must point on Templates, Layout, Partials in TYPO3

**Comment by mentAl-maZe** [comment]
Cool thx :grin:
I think I got it now :sweat_smile: 
Just one thing: is `"content-changed"` some sort of keyword or did you implement the socket yourself?

**Comment by FaraFara** [comment]
> Just one thing: is `"content-changed"` some sort of keyword or did you implement a socket yourself?

Its standart key for webpack dev server

**Comment by mentAl-maZe** [comment]
Thank you for the explanation :relaxed: 

If you where able to resolve everything please close the issue

**Comment by FaraFara** [comment]
> Here is an example of a production use case from one of my projects:
> [EXT:typo3_site_package/Resources/Private/Asstes/config/webpack/base.conf.js](https://gist.github.com/mentAl-maZe/86d9adc2c543cb2cd97e1e60d051832b)

Please show me you full this extension (templates, config... etc).  
In my config iam don't find right way..... need some examples.

**Comment by mentAl-maZe** [comment]
Will do, but I cannot expose the package directly as that would probably go over well with my client :sweat_smile: 
I'm a bit busy today (I'm a freelance dev and work on weekends) but give me until monday and I'll have uploaded an example to github which you can browse at your discretion.

**Comment by mentAl-maZe** [comment]
Sry for the delay,
I have created a repo which I plan to use as a typo3 kickstarter/bootstrapper in the future.
It's a bare bones version of my last project (removed jquery components, fonts, user data) and I'm not sure it satisfies your requirements as it's only server side rendered, but you can find a usage example for typoscript-webpack-plugin [here](https://github.com/m2sd/typo3-distribution/blob/4a7c62d4e146eb08512acf0b45b20d251fc7b02f/packages/m2s_site_package/Resources/Private/Assets/build/webpack/base.conf.js#L37-L70).

**Comment by FaraFara** [comment]
Thanx!

May iam email you, not post in here?

**Comment by mentAl-maZe** [comment]
Of course, please use my personal email:
[michael.marcenich@gmail.com](mailto:michael.marcenich@gmail.com)
