### ISSUE TITLE
Promote TYPO3 Encore

### ISSUE THREAD

**Issue by sabbelasichon** [m2sd/typoscript-webpack-plugin#4]
After a search about TYPO3 and Webpack i stumbled upon your repository.
I have also written a TYPO3 Extension to ease the integration of Webpack in TYPO3 called typo3_encore (https://github.com/sabbelasichon/typo3_encore). Under the hood it uses Webpack Encore from the Symfony Team.
Maybe we can join our knowledge and make the best implementation for everybody.

I don´t want to do marketing here, but maybe we can join forces.

Sebastian

**Comment by mentAl-maZe** [comment]
Hi Sebastian,

Sry for the late response, sadly i'm quite busy these days.

I haven't updated this extension for quite some time and your extension seems much more flexible and powerful... so i'd be happy to join forces with you, if you'll have me.

I kind of drifted a little into the node/typescript realm over the past year but I originally come from a php/symfony/typo3 background... so... let me know if I can help.

I'll deprecate this extension and add a reference to your repo later this week.

Regards

Michael

**Comment by sabbelasichon** [comment]
Hi Michael,
thanks. If you have time and could have a look into the extension let me know if we could improve something. Join forces.
